import type { Species } from '@/api/types'
import { titleCase } from '@/lib/utils'
import type { TFunction } from 'i18next'

export const DOG_BREED_IDS: readonly string[] = [
  'affenpinscher',
  'afghan_hound',
  'african_hunting_dog',
  'airedale',
  'american_staffordshire_terrier',
  'appenzeller',
  'australian_terrier',
  'basenji',
  'basset',
  'beagle',
  'bedlington_terrier',
  'bernese_mountain_dog',
  'black',
  'blenheim_spaniel',
  'bloodhound',
  'bluetick',
  'border_collie',
  'border_terrier',
  'borzoi',
  'boston_bull',
  'bouvier_des_flandres',
  'boxer',
  'brabancon_griffon',
  'briard',
  'brittany_spaniel',
  'bull_mastiff',
  'cairn',
  'cardigan',
  'chesapeake_bay_retriever',
  'chihuahua',
  'chow',
  'clumber',
  'cocker_spaniel',
  'collie',
  'curly',
  'dandie_dinmont',
  'dhole',
  'dingo',
  'doberman',
  'english_foxhound',
  'english_setter',
  'english_springer',
  'entlebucher',
  'eskimo_dog',
  'flat',
  'french_bulldog',
  'german_shepherd',
  'german_short',
  'giant_schnauzer',
  'golden_retriever',
  'gordon_setter',
  'great_dane',
  'great_pyrenees',
  'greater_swiss_mountain_dog',
  'groenendael',
  'ibizan_hound',
  'irish_setter',
  'irish_terrier',
  'irish_water_spaniel',
  'irish_wolfhound',
  'italian_greyhound',
  'japanese_spaniel',
  'keeshond',
  'kelpie',
  'kerry_blue_terrier',
  'komondor',
  'kuvasz',
  'labrador_retriever',
  'lakeland_terrier',
  'leonberg',
  'lhasa',
  'malamute',
  'malinois',
  'maltese_dog',
  'mexican_hairless',
  'miniature_pinscher',
  'miniature_poodle',
  'miniature_schnauzer',
  'newfoundland',
  'norfolk_terrier',
  'norwegian_elkhound',
  'norwich_terrier',
  'old_english_sheepdog',
  'otterhound',
  'papillon',
  'pekinese',
  'pembroke',
  'pomeranian',
  'pug',
  'redbone',
  'rhodesian_ridgeback',
  'rottweiler',
  'saint_bernard',
  'saluki',
  'samoyed',
  'schipperke',
  'scotch_terrier',
  'scottish_deerhound',
  'sealyham_terrier',
  'shetland_sheepdog',
  'shih',
  'siberian_husky',
  'silky_terrier',
  'soft',
  'staffordshire_bullterrier',
  'standard_poodle',
  'standard_schnauzer',
  'sussex_spaniel',
  'tibetan_mastiff',
  'tibetan_terrier',
  'toy_poodle',
  'toy_terrier',
  'vizsla',
  'walker_hound',
  'weimaraner',
  'welsh_springer_spaniel',
  'west_highland_white_terrier',
  'whippet',
  'wire',
  'yorkshire_terrier',
] as const

export const CAT_BREED_IDS: readonly string[] = [
  'abyssinian',
  'american_bobtail',
  'american_curl',
  'american_shorthair',
  'applehead_siamese',
  'balinese',
  'bengal',
  'birman',
  'bombay',
  'british_shorthair',
  'burmese',
  'calico',
  'cornish_rex',
  'devon_rex',
  'dilute_calico',
  'dilute_tortoiseshell',
  'domestic_long_hair',
  'domestic_medium_hair',
  'domestic_short_hair',
  'egyptian_mau',
  'exotic_shorthair',
  'extra_toes_cat___hemingway_polydactyl',
  'havana',
  'himalayan',
  'japanese_bobtail',
  'maine_coon',
  'manx',
  'munchkin',
  'nebelung',
  'norwegian_forest',
  'oriental_short_hair',
  'persian',
  'ragamuffin',
  'ragdoll',
  'russian_blue',
  'scottish_fold',
  'siamese',
  'siberian',
  'snowshoe',
  'sphynx',
  'tabby',
  'tiger',
  'tonkinese',
  'torbie',
  'tortoiseshell',
  'turkish_angora',
  'turkish_van',
  'tuxedo',
] as const

// returns the list of breed ids for the selected species
export function getBreedsForSpecies(species: Species): readonly string[] {
  if (species === 'dog') return DOG_BREED_IDS
  if (species === 'cat') return CAT_BREED_IDS
  return []
}

const MIX_SUFFIX = '_mix'

// find the split where both halves are known breed ids, so each can be translated
export function splitMixBreed(id: string): [string, string] | null {
  if (!id.endsWith(MIX_SUFFIX)) return null
  const known = new Set<string>([...DOG_BREED_IDS, ...CAT_BREED_IDS])
  const parts = id.slice(0, -MIX_SUFFIX.length).split('_')
  for (let i = 1; i < parts.length; i++) {
    const first = parts.slice(0, i).join('_')
    const second = parts.slice(i).join('_')
    if (known.has(first) && known.has(second)) return [first, second]
  }
  return null
}

// a breed id as shown to the user, a mix as "A × B"; t must reach the 'breeds' namespace
export function breedDisplayName(id: string, t: TFunction): string {
  const name = (breed: string) =>
    t(`breeds:${breed}`, { defaultValue: titleCase(breed.replace(/_/g, ' ')) })
  const mix = splitMixBreed(id)
  return mix ? `${name(mix[0])} × ${name(mix[1])}` : name(id)
}
